"""commit

Revision ID: 9364da77771a
Revises: e901fc353aeb
Create Date: 2023-11-01 16:31:05.900065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9364da77771a'
down_revision = 'e901fc353aeb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todo_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task', sa.String(length=200), nullable=True),
    sa.Column('summary', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workout', schema=None) as batch_op:
        batch_op.alter_column('pushup',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout', schema=None) as batch_op:
        batch_op.alter_column('pushup',
               existing_type=sa.INTEGER(),
               nullable=False)

    op.drop_table('todo_model')
    # ### end Alembic commands ###
